import { Header } from "@/components/Header";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Poppins } from "next/font/google";
import { SessionProvider as NextAuthProvider } from "next-auth/react";

import "@/styles/globals.scss";

const poppins = Poppins({
  weight: ["300", "400", "500"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <NextAuthProvider session={session}>
      <style jsx global>{`
        body,
        select,
        textarea,
        button {
          font: 400 1rem ${poppins.style.fontFamily};
        }
      `}</style>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Component {...pageProps} />
    </NextAuthProvider>
  );
}
